export enum ProviderConst {
  ENV_PROVIDER = 'ENV_PROVIDER',
  DATABASE_CONFIG_PROVIDER = 'DATABASE_CONFIG_PROVIDER',
  KAFKA_PROVIDER = 'KAFKA_PROVIDER',
  KAFKA_CONFIG_PROVIDER = 'KAFKA_CONFIG_PROVIDER',
}
