export enum ProviderInjector {
  ENV_PROVIDER = 'ENV_PROVIDER',
  KAFKA_PROVIDER = 'KAFKA_PROVIDER',
  KAFKA_CONFIG_PROVIDER = 'KAFKA_CONFIG_PROVIDER',
  JWT_CONFIG_PROVIDER = 'JWT_CONFIG_PROVIDER',
}
